### ISSUE TITLE
Error: Shared object "libm.so.6" not found, required by "bcrypt_lib.node"

### ISSUE THREAD

**Issue by zorro765** [yonas/meteor-freebsd#1]
Hello there, while doing some tests I ran into the following error:

/usr/local/share/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:267
                        throw(ex);
                        ^

Error: Shared object "libm.so.6" not found, required by "bcrypt_lib.node"
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/usr/local/share/meteor/.meteor/packages/npm-bcrypt/.0.7.8_2.ucabcy++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/usr/local/share/meteor/.meteor/packages/npm-bcrypt/.0.7.8_2.ucabcy++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
Exited with code: 1
Your application is crashing. Waiting for file change.

The application makes use of the accounts-password package, hence the npm-bcrypt dependency. I tried to get rid of this error by installing the "Linux® Binary Compatibility" package (https://www.freebsd.org/doc/handbook/linuxemu-lbc-install.html) that contains libm.so.6, but it hasn't changed anything.

I also tried to find the repository of the npm-bcrypt module (https://atmospherejs.com/meteor/npm-bcrypt) but it seems like there is none.

After all, I have no idea how to fix this issue. Any suggestions?
Kind regards, Michel

**Comment by yonas** [comment]
Hi Michel, I've managed to make it work, but this feels very hacky:

```
# npm install bcrypt
# npm install bindings
# rm -rf /usr/local/share/meteor/.meteor/packages/npm-bcrypt/.0.7.8_2.ucabcy++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt
# cp -Rp ~/node_modules/bcrypt /usr/local/share/meteor/.meteor/packages/npm-bcrypt/.0.7.8_2.ucabcy++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/
# cp -Rp ~/node_modules/bindings /usr/local/share/meteor/.meteor/packages/npm-bcrypt/.0.7.8_2.ucabcy++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/
```
