### ISSUE TITLE
Error with node-fibers?

### ISSUE THREAD

**Issue by SaskiFX** [yonas/meteor-freebsd#2]
When I follow your instructions on Stackoverflow (https://stackoverflow.com/questions/17606285/meteor-deployment) I get this error on a fresh jail on FreeNAS. Searching has failed me on a solution. Any ideas? The folder it mentions freebsd-x64-v8-4.6 is not there, but freebsd-x64-v8-4.5 is. 

root@external:~ # meteor
/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
        ^

Error: `/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/bin/freebsd-x64-v8-4.6/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions..js (/usr/local/share/meteor/dev_bundle/lib/node_modules/meteor-babel/register.js:29:5)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/share/meteor/tools/fs/files.js:12:13)
    at Module._compile (module.js:397:26)
root@external:~ #

**Comment by yonas** [comment]
I haven't posted anything on that Stackoverflow question, but you might want to try symbolically linking freebsd-x64-v8-4.6 to freebsd-x64-v8-4.5. For eg:

```
cd /usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/bin
ln -s freebsd-x64-v8-4.5 freebsd-x64-v8-4.6
```

**Comment by SaskiFX** [comment]
Shoot, sorry, I linked the wrong thread. :) I meant this one, if you were the one who replied with the solution:
https://stackoverflow.com/questions/13819199/how-to-install-meteor-on-freebsd

I tried linking the files, and now get a different error at least.

root@external:/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/bin # meteor
module.js:422
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Shared object "libc++.so.1" not found, required by "fibers.node"
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/fibers.js:20:37)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions..js (/usr/local/share/meteor/dev_bundle/lib/node_modules/meteor-babel/register.js:29:5)
root@external:/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/bin #

Doing a pkg install libc++ got that error to go away, and then gave me an error about missing libcxxrt.so.1. So I noticed I had libcxxrt.so, and linked it to libcxxrt.so.1. No idea if that should have worked or not, but now I get one last error:

root@external:/usr/local/lib # meteor
module.js:422
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/share/meteor/dev_bundle/lib/node_modules/fibers/fibers.js:20:37)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions..js (/usr/local/share/meteor/dev_bundle/lib/node_modules/meteor-babel/register.js:29:5)
root@external:/usr/local/lib #

Not sure how to get around this one.

**Comment by linegel** [comment]
have same problem as @SaskiFX and cant fix that, may be @yonas have some ideas?

**Comment by yonas** [comment]
@linegel The only thing I can think of right now is to try symbolically linking freebsd-x64-v8-4.6 to freebsd-x64-v8-4.5

**Comment by yonas** [comment]
@linegel @SaskiFX  Can you try using https://github.com/4commerce-technologies-AG/meteor instead and let me know if you still get this error?

**Comment by linegel** [comment]
@yonas https://github.com/4commerce-technologies-AG/meteor  work perfect, we use that in production on FreeBSD 10.2
